version: 2.3.1.{build}
os: Windows Server 2012
platform: Any CPU
configuration: Release
before_build:
- nuget restore src/Logikfabrik.Umbraco.Jet.sln
build:
  project: src/Logikfabrik.Umbraco.Jet.sln
  verbosity: detailed