version: 3.2.0.{build}
os: Visual Studio 2015
platform: Any CPU
configuration: Release
before_build:
- nuget restore src/Logikfabrik.Umbraco.Jet.sln
build:
  project: src/Logikfabrik.Umbraco.Jet.sln
  publish_nuget: true
  verbosity: normal